# -*- coding: utf-8 -*-
"""DeepLearning_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RQ9vYqpsFva3q8-nGaL4WUPGjSEityWM
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.python.keras import layers
from keras.optimizers import Adam
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten
from keras.layers import Conv2D,MaxPooling2D
import shutil
# %matplotlib inline

!unzip /content/drive/MyDrive/Emotion_Dataset.zip

# make a train folder
# make a test folder
# within train : negative, neutral, positive
# within test : negative, neutral, positive

!mkdir actual_train
!mkdir actual_test

import os 
os.mkdir('/content/actual_train/neutral') # train_neutral
os.mkdir('/content/actual_train/positive') # train_positive
os.mkdir('/content/actual_train/negative') # train_negative

os.mkdir('/content/actual_test/neutral') # test_neutral
os.mkdir('/content/actual_test/positive') # test_positive
os.mkdir('/content/actual_test/negative') # test_negative

def moving_files(origin,target):
  
  files = os.listdir(origin)

  for file_name in files : 
    shutil.copy(origin+file_name, target+file_name)

  print("Files are copied successfully")

moving_files('/content/train/angry/','/content/actual_train/negative/')
moving_files('/content/train/disgust/','/content/actual_train/negative/')
moving_files('/content/train/fear/','/content/actual_train/negative/')
moving_files('/content/train/sad/','/content/actual_train/negative/')

moving_files('/content/train/happy/','/content/actual_train/positive/')
moving_files('/content/train/surprise/','/content/actual_train/positive/')

moving_files('/content/train/neutral/','/content/actual_train/neutral/')



moving_files('/content/test/angry/','/content/actual_test/negative/')
moving_files('/content/test/disgust/','/content/actual_test/negative/')
moving_files('/content/test/fear/','/content/actual_test/negative/')
moving_files('/content/test/sad/','/content/actual_test/negative/')

moving_files('/content/test/happy/','/content/actual_test/positive/')
moving_files('/content/test/surprise/','/content/actual_test/positive/')

moving_files('/content/test/neutral/','/content/actual_test/neutral/')

train_gen = ImageDataGenerator(rescale = 1./255,zoom_range = 0.2,shear_range = 0.25,rotation_range = 25,horizontal_flip = True,fill_mode = 'nearest')
train_image = train_gen.flow_from_directory(directory = '/content/actual_train', color_mode = 'grayscale', target_size = (48,48), batch_size = 32,class_mode = "categorical", shuffle = True)

test_gen = ImageDataGenerator(rescale = 1./255)
test_image = test_gen.flow_from_directory(directory = '/content/actual_test', color_mode = 'grayscale', target_size = (48,48), batch_size = 32,class_mode = "categorical", shuffle = True)

img, label = train_image.__next__()
print(img,label)

model = Sequential()

model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(48,48,1)))

model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.1))

model.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.1))

model.add(Conv2D(256, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.1))

model.add(Conv2D(256, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.1))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(3, activation='softmax'))

model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

history=model.fit(train_image,
                steps_per_epoch=100,
                epochs=1,
                validation_data=test_image,
                validation_steps=100)
model.save('hkdfhsk.h5')

"""MODEL 2"""

model2 = Sequential()

model2.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(48, 48, 3)))
model2.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model2.add(MaxPooling2D(pool_size=(2, 2)))
model2.add(Dropout(0.25))

model2.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
model2.add(MaxPooling2D(pool_size=(2, 2)))
model2.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
model2.add(MaxPooling2D(pool_size=(2, 2)))
model2.add(Dropout(0.25))

model2.add(Flatten())
model2.add(Dense(1024, activation='relu'))
model2.add(Dropout(0.5))
model2.add(Dense(3, activation='softmax'))

model2.compile(loss='categorical_crossentropy', optimizer=Adam(learning_rate=0.0001), metrics=['accuracy'])

model2.summary()

model2_info = model2.fit(train_image,
                steps_per_epoch=450,
                epochs=60,
                validation_data=test_image,
                validation_steps=100)

"""MODEL 3"""

model3 = Sequential()
model3.build(input_shape =(48,48,1))

model3.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(48,48,1)))

model3.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model3.add(MaxPooling2D(pool_size=(2, 2)))
model3.add(Dropout(0.1))

model3.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
model3.add(MaxPooling2D(pool_size=(2, 2)))
model3.add(Dropout(0.1))

model3.add(Conv2D(256, kernel_size=(3, 3), activation='relu'))
model3.add(MaxPooling2D(pool_size=(2, 2)))
model3.add(Dropout(0.1))

model3.add(Flatten())
model3.add(Dense(512, activation='relu'))
model3.add(Dropout(0.2))

model3.add(Dense(3, activation='softmax'))

model3.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

epochs=50

history=model3.fit(train_image,
                steps_per_epoch=300,
                epochs=epochs,
                validation_data=test_image,
                validation_steps=100)

model3.save('final_model_file.h5')

model3.summary()

